### PR TITLE
Use llvm-config to set env variables

### PR DESCRIPTION
**Pull request by bertschneider**

### CODE REVIEW

**Comment by kyakdan** [comment]
@bertschneider Is this PR still relevant?

**Comment by bertschneider** [comment]
I like the approach to use `llvm-config` to set all needed environment variables more than the hard coded path variant. If you also think so, we could refactor the current pipeline scripts accordingly.

**Comment by 0xricksanchez** [comment]
This looks trivial to fix and IMO brings value as hard-coding things = bad. What stops us from pushing this forward?

**Review by kyakdan — APPROVED** [review]
I've squashed the commits and slightly adjusted resolution of `CC` and `CXX`.

**Pull request merged**
